################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on Commissions
#'
#' This dataset includes data on Commissions of the European Union
#' (1958-2021). There is one observation per Commission. The data indicates
#' the national party and European political group of the President of the
#' Commission and the start and end dates of each Commission. The Mansholt
#' Commission is treated as its own Commission. The Marín Commission is
#' treated as part of the Santer Commission.
#'
#' @format A data frame with 25 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{commission_id}{Numeric. The ID number that uniquely identifies each
#' Commission.}
#' \item{commission}{String. The name of the Commission.}
#' \item{full_name}{String. The full name of the President of the Commission.}
#' \item{full_name_latin}{String. The full name of the President of the
#' Commission using only basic Latin characters.}
#' \item{last_name}{String. The last name of the President of the Commission.}
#' \item{last_name_latin}{String. The last name of the President of the
#' Commission using only basic Latin characters.}
#' \item{first_name}{String. The first name of the President of the
#' Commission.}
#' \item{first_name_latin}{String. The first name of the President of the
#' Commission using only basic Latin characters.}
#' \item{member_state_id}{Numeric. An ID number that uniquely identifies each
#' member state.}
#' \item{member_state}{String. The name of the President of the Commission's
#' member state.}
#' \item{member_state_code}{String. The two-letter code assigned by the
#' Commission to the President of the Commission's member state.}
#' \item{national_party_code}{String. The common abbreviation of the President
#' of the Commission's national political party.}
#' \item{national_party_name}{String. The name of the President of the
#' Commission's national political party in the President's member state's
#' official language.}
#' \item{national_party_name_english}{String. The name of the President of the
#' Commission's national political party in English.}
#' \item{political_group_code}{String. The common abbreviation of the
#' political group.}
#' \item{political_group_name}{String. The name of the President of the
#' Commission's political group.}
#' \item{start_date}{Date. The start date of the Commission.}
#' \item{start_year}{Numeric. The start year of the Commission.}
#' \item{start_month}{Numeric. The start month of the Commission.}
#' \item{start_day}{Numeric. The start day of the Commission.}
#' \item{end_date}{Date. The end date of the Commission.}
#' \item{end_year}{Numeric. The start year of the Commission.}
#' \item{end_month}{Numeric. The start month of the Commission.}
#' \item{end_day}{Numeric. The end day of the Commission.}
#' }
"commissions"

################################################################################
# end R script
################################################################################
