################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on commissioners
#' 
#' This dataset includes data on Commissioners (1958-2021). There is one
#' observation per individual who has served as a Commissioner. The dataset
#' indicates the national party and European political group of each
#' individual, the Commissions that the individual served during, and the
#' earliest and latest dates that each individual was in office.
#' 
#' @format A data frame with 26 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{commissioner_id}{\code{numeric}. An ID number that uniquely
#' identifies each individual who was served as a Commissioner.}
#' \item{full_name}{\code{string}. The full name of the Commissioner.}
#' \item{full_name_latin}{\code{string}. The full name of the Commissioner
#' using only basic Latin characters.}
#' \item{last_name}{\code{string}. The last name of the Commissioner.}
#' \item{last_name_latin}{\code{string}. The last name of the Commissioner
#' using only basic Latin characters.}
#' \item{first_name}{\code{string}. The first name of the Commissioner.}
#' \item{first_name_latin}{\code{string}. The first name of the Commissioner
#' using only basic Latin characters.}
#' \item{member_state_id}{\code{numeric}. An ID number that uniquely
#' identifies each member state.}
#' \item{member_state}{\code{string}. The name of the Commissioner's member
#' state.}
#' \item{member_state_code}{\code{string}. The two-letter code assigned by the
#' Commission to the Commissioner's member state.}
#' \item{national_party_code}{\code{string}. The common abbreviation of the
#' Commissioner's national political party.}
#' \item{national_party_name}{\code{string}. The name of the Commissioner's
#' national political party in the Commissioner's member state's official
#' language.}
#' \item{national_party_name_english}{\code{string}. The name of the
#' Commissioner's national political party in English.}
#' \item{political_group_code}{\code{string}. The common abbreviation of the
#' political group.}
#' \item{political_group_name}{\code{string}. The name of the Commissioner's
#' political group.}
#' \item{commissions}{\code{string}. A list of the Commissions in which the
#' Commissioner served, separated by a comma. }
#' \item{count_commissions}{\code{numeric}. The number of Commissions in which
#' the Commissioner served.}
#' \item{start_date}{\code{date}. The start date of the Commissioner across
#' all Commissions in which the Commissioner served.}
#' \item{start_year}{\code{numeric}. The start year of the Commissioner across
#' all Commissions in which the Commissioner served.}
#' \item{start_month}{\code{numeric}. The start month of the Commissioner
#' across all Commissions in which the Commissioner served.}
#' \item{start_day}{\code{numeric}. The start day of the Commissioner across
#' all Commissions in which the Commissioner served.}
#' \item{end_date}{\code{date}. The end date of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{end_year}{\code{numeric}. The start year of the Commissioner across
#' all Commissions in which the Commissioner served.}
#' \item{end_month}{\code{numeric}. The start month of the Commissioner across
#' all Commissions in which the Commissioner served.}
#' \item{end_day}{\code{numeric}. The end day of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' }
"commissioners"

################################################################################
# end R script
################################################################################

