################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on commissioners
#' 
#' This dataset includes data on Commissioners (1958-2021). There is one
#' observation per individual who has served as a Commissioner. The dataset
#' indicates the national party and European political group of each
#' individual, the Commissions that the individual served during, and the
#' earliest and latest dates that each individual was in office.
#' 
#' @format A data frame with 26 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{commissioner_id}{Numeric. An ID number that uniquely identifies each
#' individual who was served as a Commissioner.}
#' \item{full_name}{String. The full name of the Commissioner.}
#' \item{full_name_latin}{String. The full name of the Commissioner using only
#' basic Latin characters.}
#' \item{last_name}{String. The last name of the Commissioner.}
#' \item{last_name_latin}{String. The last name of the Commissioner using only
#' basic Latin characters.}
#' \item{first_name}{String. The first name of the Commissioner.}
#' \item{first_name_latin}{String. The first name of the Commissioner using
#' only basic Latin characters.}
#' \item{member_state_id}{Numeric. An ID number that uniquely identifies each
#' member state.}
#' \item{member_state}{String. The name of the Commissioner's member state.}
#' \item{member_state_code}{String. The two-letter code assigned by the
#' Commission to the Commissioner's member state.}
#' \item{national_party_code}{String. The common abbreviation of the
#' Commissioner's national political party.}
#' \item{national_party_name}{String. The name of the Commissioner's national
#' political party in the Commissioner's member state's official language.}
#' \item{national_party_name_english}{String. The name of the Commissioner's
#' national political party in English.}
#' \item{political_group_code}{String. The common abbreviation of the
#' political group.}
#' \item{political_group_name}{String. The name of the Commissioner's
#' political group.}
#' \item{commissions}{String. A list of the Commissions in which the
#' Commissioner served, separated by a comma. }
#' \item{count_commissions}{Numeric. The number of Commissions in which the
#' Commissioner served.}
#' \item{start_date}{Date. The start date of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{start_year}{Numeric. The start year of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{start_month}{Numeric. The start month of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{start_day}{Numeric. The start day of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{end_date}{Date. The end date of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{end_year}{Numeric. The start year of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{end_month}{Numeric. The start month of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' \item{end_day}{Numeric. The end day of the Commissioner across all
#' Commissions in which the Commissioner served.}
#' }
"commissioners"

################################################################################
# end R script
################################################################################

