################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on departments (by Commission)
#'
#' This dataset includes data on departments of the Commission, including
#' Directorates-General and service departments (1958-2021). There is one
#' observation per department per Commission. This dataset provides a snapshot
#' of each Commission at the time that the first directory is published. For
#' Commissions that come into office early in a year, the first directory is
#' usually published later that year. For Commissions that come into office
#' late in a year, the first directory is usually published early the next
#' year. The exception is the Prodi Commission. The data for this Commission
#' comes from the earliest available directory.
#'
#' @format A data frame with 18 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{commission_id}{Numeric. The ID number that uniquely identifies each
#' Commission. See the \code{commissions} dataset.}
#' \item{commission}{String. The name of the Commission. See the
#' \code{commissions} dataset.}
#' \item{start_date}{Date. The start date of the Commission.}
#' \item{start_year}{Numeric. The start year of the Commission.}
#' \item{start_month}{Numeric. The start month of the Commission.}
#' \item{start_day}{Numeric. The start day of the Commission.}
#' \item{end_date}{Date. The end date of the Commission.}
#' \item{end_year}{Numeric. The start year of the Commission.}
#' \item{end_month}{Numeric. The start month of the Commission.}
#' \item{end_day}{Numeric. The end day of the Commission.}
#' \item{department_type_id}{Numeric. An ID number that uniquely identifies
#' the type of the department. Coded \code{1} for \code{Directorate-General}
#' and \code{2} for \code{Service department}. See the variable
#' \code{department_type}.}
#' \item{department_type}{String. The type of the department. Either
#' \code{Directorate-General} or \code{Service department}.}
#' \item{department_id}{Numeric. An ID number that uniquely identifies each
#' department. See the \code{departments} dataset.}
#' \item{department_name}{String. The name of the department.}
#' \item{department_code}{String. The common abbreviation of the department.
#' Coded \code{Not applicable} of there is not an abbreviation for the
#' department. Coded \code{None} for all Commissions prior to the Prodi
#' Commission.}
#' \item{policy_area}{String. The name of the policy area. See the
#' \code{policy_areas} dataset.}
#' \item{current_department_name}{String. The name of the current department.
#' See the \code{departments} dataset.}
#' }
"departments_by_commission"

################################################################################
# end R script
################################################################################

