################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on departments
#' 
#' This dataset includes data on departments of the Commission, including
#' Directorates-General and service departments (1958-2021). There is one
#' observation per unique department. A new observation is created every time
#' a department is renamed, even if the department itself does not change.
#' This allows you to track changes in department nomenclature over time.
#' 
#' @format A data frame with 13 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{department_id}{Numeric. An ID number that uniquely identifies each
#' department.}
#' \item{department_name}{String. The name of the department.}
#' \item{first_commission_id}{Numeric. The ID number of the first Commission
#' in which the department appeared. See the \code{commissions} dataset.}
#' \item{first_commission}{String. The first Commission in which the
#' department appeared.}
#' \item{commissions}{String. A list of the Commissions in which the
#' department appeared, separated by a comma. }
#' \item{count_commissions}{Numeric. The number of Commissions in which the
#' department appeared.}
#' \item{current_department}{Dummy. A dummy variable indicating whether the
#' department is a current department under the von der Leyen Commission.
#' Coded \code{1} if the department is a current department and \code{0}
#' otherwise. }
#' \item{department_type_id}{Numeric. An ID number that uniquely identifies
#' the type of the department. Coded \code{1} for \code{Directorate-General}
#' and \code{2} for \code{Service department}. See the variable
#' \code{department_type}.}
#' \item{department_type}{String. The type of the department. Either
#' \code{Directorate-General} or \code{Service department}.}
#' \item{department_code}{String. The common abbreviation of the department.
#' Coded \code{Not applicable} of there is not an abbreviation for the
#' department. Coded \code{None} for all Commissions prior to the Prodi
#' Commission.}
#' \item{policy_area}{String. The name of the policy area. See the
#' \code{policy_areas} dataset.}
#' \item{current_department_name}{String. The name of the current department.
#' See the \code{departments} dataset.}
#' }
"departments"

################################################################################
# end R script
################################################################################

