################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on department histories
#'
#' This dataset includes data on the histories of the current departments of
#' the Commission, including Directorates-General and service departments
#' (1958-2021). There is one observation per historical interval in which the
#' nomenclature of a department is constant. Unlike allocations, intervals can
#' span Commissions. By sorting the dataset by current department, you can see
#' the evolution of each department over time. The dataset indicates the
#' Commissions associated with each interval and the start and end dates of
#' each interval.
#'
#' @format A data frame with 21 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{current_deparment_id}{Numeric. An ID number that uniquely identifies
#' each current department. See the \code{departments} dataset.}
#' \item{current_department_name}{String. The name of the current department.
#' See the \code{departments} dataset.}
#' \item{current_department_code}{String. The common abbreviation of the
#' current department. Coded \code{Not applicable} of there is not an
#' abbreviation for the department. Coded \code{None} for all Commissions
#' prior to the Prodi Commission. See the \code{departments} dataset.}
#' \item{current_department_type_id}{Numeric. An ID number that uniquely
#' identifies the type of the current department. Coded \code{1} for
#' \code{Directorate-General} and \code{2} for \code{Service department}. See
#' the variable \code{department_type}.}
#' \item{current_department_type}{String. The type of the current department.
#' Either \code{Directorate-General} or \code{Service department}.}
#' \item{department_id}{Numeric. An ID number that uniquely identifies each
#' department. See the \code{departments} dataset.}
#' \item{department_name}{String. The name of the department.}
#' \item{department_code}{String. The common abbreviation of the department.
#' Coded \code{Not applicable} of there is not an abbreviation for the
#' department. Coded \code{None} for all Commissions prior to the Prodi
#' Commission.}
#' \item{department_type_id}{Numeric. An ID number that uniquely identifies
#' the type of the department. Coded \code{1} for \code{Directorate-General}
#' and \code{2} for \code{Service department}. See the variable
#' \code{department_type}.}
#' \item{department_type}{String. The type of the department. Either
#' \code{Directorate-General} or \code{Service department}.}
#' \item{commissions}{String. A list of the Commissions in which the
#' department appeared, separated by a comma.}
#' \item{count_commissions}{Numeric. The number of Commissions in which the
#' department appeared.}
#' \item{start_date}{Date. The start date of the historical interval.
#' Historical intervals can cross Commissions.}
#' \item{start_year}{Numeric. The start year of the historical interval.
#' Historical intervals can cross Commissions.}
#' \item{start_month}{Numeric. The start month of the historical interval.
#' Historical intervals can cross Commissions.}
#' \item{start_day}{Numeric. The start day of the historical interval.
#' Historical intervals can cross Commissions.}
#' \item{end_date}{Date. The end date of the historical interval. Historical
#' intervals can cross Commissions.}
#' \item{end_year}{Numeric. The start year of the historical interval.
#' Historical intervals can cross Commissions.}
#' \item{end_month}{Numeric. The start month of the historical interval.
#' Historical intervals can cross Commissions.}
#' \item{end_day}{Numeric. The end day of the historical interval. Historical
#' intervals can cross Commissions.}
#' }
"department_histories"

################################################################################
# end R script
################################################################################
