################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Data on policy area allocations
#' 
#' This dataset includes data on policy area allocations (1958-2021). There is
#' one observation per policy area allocation per Commission (i.e., one
#' observation per policy area per Commissioner per Commission). A new
#' observation is created every time a change in the portfolio of a
#' Commissioner leads to a change in who oversees a policy area. There can be
#' multiple observations per individual per Commission if an individual
#' oversees multiple policy areas or if the individual's portfolio changes
#' during the Commission. Policy area allocations do not span Commissions. If
#' a Commissioner oversees a policy area for more than one Commission, there
#' will be multiple observations, one for each Commission. The dataset
#' indicates the start and end dates of each policy allocation.
#' 
#' @format A data frame with 28 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{commission_id}{\code{numeric}. The ID number that uniquely identifies
#' each Commission. See the \code{commissions} dataset.}
#' \item{commission}{\code{string}. The name of the Commission. See the
#' \code{commissions} dataset.}
#' \item{commissioner_id}{\code{numeric}. An ID number that uniquely
#' identifies each individual who was served as a Commissioner. See the
#' \code{commissioners} dataset.}
#' \item{full_name}{\code{string}. The full name of the Commissioner.}
#' \item{full_name_latin}{\code{string}. The full name of the Commissioner
#' using only basic Latin characters.}
#' \item{last_name}{\code{string}. The last name of the Commissioner.}
#' \item{last_name_latin}{\code{string}. The last name of the Commissioner
#' using only basic Latin characters.}
#' \item{first_name}{\code{string}. The first name of the Commissioner.}
#' \item{first_name_latin}{\code{string}. The first name of the Commissioner
#' using only basic Latin characters.}
#' \item{member_state_id}{\code{numeric}. An ID number that uniquely
#' identifies each member state.}
#' \item{member_state}{\code{string}. The name of the Commissioner's member
#' state.}
#' \item{member_state_code}{\code{string}. The two-letter code assigned by the
#' Commission to the Commissioner's member state.}
#' \item{national_party_code}{\code{string}. The common abbreviation of the
#' Commissioner's national political party.}
#' \item{national_party_name}{\code{string}. The name of the Commissioner's
#' national political party in the Commissioner's member state's official
#' language.}
#' \item{national_party_name_english}{\code{string}. The name of the
#' Commissioner's national political party in English.}
#' \item{political_group_code}{\code{string}. The common abbreviation of the
#' political group.}
#' \item{political_group_name}{\code{string}. The name of the Commissioner's
#' political group.}
#' \item{start_date}{\code{date}. The start date of the allocation.
#' Allocations do not cross Commissions.}
#' \item{start_year}{\code{numeric}. The start year of the allocation.
#' Allocations do not cross Commissions.}
#' \item{start_month}{\code{numeric}. The start month of the allocation.
#' Allocations do not cross Commissions.}
#' \item{start_day}{\code{numeric}. The start day of the allocation.
#' Allocations do not cross Commissions.}
#' \item{end_date}{\code{date}. The end date of the allocation. Allocations do
#' not cross Commissions.}
#' \item{end_year}{\code{numeric}. The start year of the allocation.
#' Allocations do not cross Commissions.}
#' \item{end_month}{\code{numeric}. The start month of the allocation.
#' Allocations do not cross Commissions.}
#' \item{end_day}{\code{numeric}. The end day of the allocation. Allocations
#' do not cross Commissions.}
#' \item{policy_area_id}{\code{numeric}. An ID number that uniquely identifies
#' each policy area. See the \code{policy_areas} dataset.}
#' \item{policy_area}{\code{numeric}. The name of the policy area. See the
#' \code{policy_areas} dataset.}
#' }
"policy_area_allocations"

################################################################################
# end R script
################################################################################

